# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         HTTP-ProxyPAC
version:      0.01
version_from: lib/HTTP/ProxyPAC.pm
installdirs:  site
requires:
    JavaScript:                    0
    LWP:                           5.6
    Scalar::Util:                  0
    Test::More:                    0.32
    URI:                           1.3

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
